### ISSUE TITLE
Snapshots not detected on Podman?

### ISSUE THREAD

**Issue by 20kdc** [ludus-leonis/FreeBeeGee#6]
While deploying the Docker container to a personal Nomad v1.5.3 instance via Podman, it turned out that the data volume overrode the server snapshots, making it impossible to create a room.
The snapshot list shows no snapshots and attempting creation gives the error "The selected snapshot contains errors and can't be loaded."
This might also apply to non-Nomad deployments, but I'm not sure.

Workaround: Manually copy the snapshots directory.

HCL used for deployment:
[pathos2.hcl.txt](https://github.com/ludus-leonis/FreeBeeGee/files/12535958/pathos2.hcl.txt)

**Comment by ludus-leonis** [comment]
Yes, the data folder needs to be prepopulated and can't just be mapped with an empty volume. I guess I should update the the INSTALL.md to reflect that. 

So you could
- either add the data folder content from a FBG zip to your volume before mounting (the snapshots dir, config file), 
- or mount a volume as data/rooms instead of data itself, so FBG would create dynamic data / room instances in there for backup. In this scenario you would not have access to the config file from the outsite though.

This is not Nomad related. Not sure how other docker apps handle this. If it is common that mounted empty volumes are autodetected and re-populated, I could add that to the backlog.

**Comment by 20kdc** [comment]
I'm not aware of mounted empty volumes being repopulated being a thing.
That said, my experience is limited (hence my uncertainty as to if it was Nomad-specific).
I think updating the INSTALL.md and adding some indicator if the server still gets into that state would be enough.

**Comment by ludus-leonis** [comment]
I updated the INSTALL.md to cover mounting room data, config file and /data mounting.

fixed in 0.21.0

**Comment by 20kdc** [comment]
Alrighty, thank you! That should avoid problems in future.
